name-template: 'v$RESOLVED_VERSION'
tag-template: 'v$RESOLVED_VERSION'
categories:
  - title: '🚀 Features'
    labels:
      - feat
  - title: '🐛 Fixes'
    labels:
      - fix
  - title: '🧰 Maintenance'
    labels:
      - chore
change-template: '- $TITLE (#$NUMBER)'
no-changes-template: 'No changes in this release.'