name: 'Install dependencies'
description: 'Install dependencies'

runs:
  using: composite
  steps:
    - name: Install system dependencies
      shell: bash
      run: |
        sudo apt-get update
        sudo apt-get install -y libudev-dev libusb-1.0-0-dev

    - name: Install Foundry
      uses: foundry-rs/foundry-toolchain@v1

    - name: Install Bun
      uses: oven-sh/setup-bun@v2
      with:
        bun-version: 1.2.2

    - name: Install Node.js dependencies
      working-directory: contracts
      shell: bash
      run: bun install


