services:
  redis-db:
    extends:
      file: ./services/redis.yml
      service: redis-db
    profiles:
      - blockscout

  db-init:
    extends:
      file: ./services/db.yml
      service: db-init
    profiles:
      - blockscout

  db:
    depends_on:
      db-init:
        condition: service_completed_successfully
    extends:
      file: ./services/db.yml
      service: db
    profiles:
      - blockscout

  backend:
    depends_on:
      - db
      - redis-db
    extends:
      file: ./services/backend.yml
      service: backend
    links:
      - db:database
    environment:
        ETHEREUM_JSONRPC_VARIANT: 'geth'
    profiles:
      - blockscout

  visualizer:
    extends:
      file: ./services/visualizer.yml
      service: visualizer
    profiles:
      - blockscout

  sig-provider:
    extends:
      file: ./services/sig-provider.yml
      service: sig-provider
    profiles:
      - blockscout

  frontend:
    depends_on:
      - backend
    extends:
      file: ./services/frontend.yml
      service: frontend
    profiles:
      - blockscout

  stats-db-init:
    extends:
      file: ./services/stats.yml
      service: stats-db-init
    profiles:
      - blockscout

  stats-db:
    depends_on:
      stats-db-init:
        condition: service_completed_successfully
    extends:
      file: ./services/stats.yml
      service: stats-db
    profiles:
      - blockscout

  stats:
    depends_on:
      - stats-db
      - backend
    extends:
      file: ./services/stats.yml
      service: stats
    profiles:
      - blockscout

  user-ops-indexer:
    depends_on:
      - db
      - backend
    extends:
      file: ./services/user-ops-indexer.yml
      service: user-ops-indexer
    profiles:
      - blockscout

  proxy:
    depends_on:
      - backend
      - frontend
      - stats
    extends:
      file: ./services/nginx.yml
      service: proxy
    profiles:
      - blockscout
