export interface AuthBlob {
    username: string;
    nonce: string;
}

export interface AuthenticationRequest {
    blob: AuthBlob;
    blobSignature: string;
}

export interface AuctionRequest {
    id?: string; // must be a UUID V4 generated by frontend
    srcChainId: number;
    dstChainId: number;
    srcTokenAddress: string;
    dstTokenAddress: string;
    amountIn: bigint; // must be an integer representing the smallest denomination of the token
}

export interface AuctionQuote {
    id?: string;
    request: {
        srcChainId: number;
        dstChainId: number;
        srcTokenAddress: string;
        dstTokenAddress: string;
        amountIn: bigint;
    },
    amountOut: bigint;
    settlementReceiverAddress: string;
    timestamp: number;
}

export interface OpenEventLog {
    address: string;
    topics: string[];
    data: string;
    blockNumber: string;
    transactionHash: string;
    transactionIndex: string;
    blockHash: string;
    logIndex: string;
    removed: boolean;
}

export interface AuctionResult {
    type: string;
    orderId: string;
    settlementReceiverAddress: string;
    amountOut: bigint;
    signature: string;
    openEvent: OpenEventLog;
}

export interface AuthAttempt {
    username: string;
    blobHeader: string;
    nonce: string;
    sig: `0x${string}`;
}
