import type {OrderData} from "../blockchain/types.ts";

export interface AuctionRequest {
    id?: string; // must be a UUID V4 generated by frontend
    srcChainId: number;
    dstChainId: number;
    srcTokenAddress: string;
    dstTokenAddress: string;
    amountIn: bigint; // must be an integer representing the smallest denomination of the token
}

export interface AuctionQuote {
    id?: string;
    request: {
        srcChainId: number;
        dstChainId: number;
        srcTokenAddress: `0x${string}`;
        dstTokenAddress: `0x${string}`;
        amountIn: bigint;
    },
    amountOut: bigint;
    settlementReceiverAddress: `0x${string}`;
    timestamp: number;
}

export interface AuctionResult {
    settlementReceiverAddress: `0x${string}`;
    amountOut: bigint;
    orderId: string;
    orderData: OrderData;
}
