[package]
name = "t1-reth"
version = "0.1.0"
edition = "2024"

[dependencies]
reth = { git = "https://github.com/paradigmxyz/reth.git", tag = "v1.1.5" }               # Reth
reth-exex = { git = "https://github.com/paradigmxyz/reth.git", tag = "v1.1.5" }                          # Execution Extensions
reth-node-ethereum = { git = "https://github.com/paradigmxyz/reth.git", tag = "v1.1.5" }                 # Ethereum Node implementation
reth-tracing = { git = "https://github.com/paradigmxyz/reth.git", tag = "v1.1.5" }                       # Logging

eyre = "0.6"         # Easy error handling
futures-util = "0.3" # Stream utilities for consuming notifications
