name: "Bump, Tag, and Release"

on:
  pull_request:
    types:
      - opened
      - reopened
      - synchronize
      - ready_for_review
  workflow_dispatch:
    inputs:
      release_type:
        description: "Select release type: patch, minor, or major"
        required: true
        type: choice
        options:
          - patch
          - minor
          - major

permissions:
  contents: write
  pull-requests: write  

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - name: "Check out the repo"
        uses: "actions/checkout@v4.1.1"

      - name: "Install Bun"
        uses: "oven-sh/setup-bun@v2"

      - name: "Install Node.js dependencies"
        run: bun install

      - name: Bump Tag Version
        id: tag
        uses: mathieudutour/github-tag-action@v6.1
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          tag_prefix: 'v'
          default_bump: ${{ github.event.inputs.release_type }}
          create_annotated_tag: true

      - name: Skip if no new tag
        if: steps.tag.outputs.new_version == ''
        run: |
          echo "No new version to release."
          exit 0

      - name: Update Versions
        run: npm run bump ${{ steps.tag.outputs.new_version }}

      - name: Commit and Push Version Changes to New Branch
        run: |
          BRANCH="release-bump-v${{ steps.tag.outputs.new_version }}"
          git config user.name "GitHub Actions"
          git config user.email "actions@github.com"
          git checkout -b "$BRANCH"
          if git diff --quiet; then
            echo "No changes to commit"
            exit 0
          fi
          git add .
          git commit -m "chore: bump version to ${{ steps.tag.outputs.new_version }}"
          git push origin "$BRANCH"
      
      - name: Create Pull Request
        uses: peter-evans/create-pull-request@v5.0.2
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          branch: release-bump-v${{ steps.tag.outputs.new_version }}
          title: "Chore: Bump version to v${{ steps.tag.outputs.new_version }}"
          base: canary
          body: |
            This PR was automatically generated by the release workflow.
          labels: automated, release
          committer: GitHub Actions <actions@github.com>
          author: GitHub Actions <actions@github.com>

      # - name: Create GitHub Release with Notes
      #   uses: release-drafter/release-drafter@v5
      #   with:
      #     tag: ${{ steps.tag.outputs.new_tag }}
      #     name: Release ${{ steps.tag.outputs.new_tag }}
      #   env:
      #     GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}