name: "Bump, Tag, and Release"

on:
  workflow_dispatch:
    inputs:
      release_type:
        description: "Select release type: patch, minor, or major"
        required: true
        type: choice
        options:
          - patch
          - minor
          - major
  pull_request:
    types:
      - closed

permissions:
  contents: write
  pull-requests: write

jobs:
  release:
    if: github.event_name == 'workflow_dispatch'
    runs-on: ubuntu-latest
    steps:
      - name: "Check out the repo"
        uses: actions/checkout@v4.1.1

      - name: "Install Bun"
        uses: oven-sh/setup-bun@v2

      - name: "Install Node.js dependencies"
        run: bun install

      - name: Update, Commit, and Push Version Changes
        run: |
          BRANCH="release-bump-v${{ github.run_number }}"
          git config user.name "GitHub Actions"
          git config user.email "actions@github.com"
          git checkout -b "$BRANCH"

          npm run bump ${{ github.event.inputs.release_type }}

          echo "Git status after bump:"
          git status
          echo "Git diff:"
          git diff

          git add .
          if git diff --cached --quiet; then
            echo "No changes to commit"
            exit 0
          fi

          git commit -s -m "Chore: Bump version to v$(node -p \"require('./package.json').version\")"
          git push origin "$BRANCH"

      - name: Create Pull Request
        uses: peter-evans/create-pull-request@v5.0.2
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          branch: release-bump-v${{ github.run_number }}
          title: "Chore: Bump version to v$(node -p \"require('./package.json').version\")"
          base: canary
          body: |
            This PR was automatically generated by the release workflow.
          labels: automated, release
          committer: t1 GitHub Actions <github@t1protocol.com>
          author: t1 GitHub Actions <github@t1protocol.com>
          signoff: true
          delete-branch: false

  tag_and_release_notes:
    if: |
      github.event.pull_request.merged == true &&
      startsWith(github.event.pull_request.title, 'Chore: Bump version to v')
    runs-on: ubuntu-latest

    steps:
      - name: Check out the repo at merge commit
        uses: actions/checkout@v4.1.1
        with:
          ref: ${{ github.event.pull_request.merge_commit_sha }}

      - name: Extract version from PR title
        id: extract
        run: |
          VERSION=$(echo "${{ github.event.pull_request.title }}" | grep -oE 'v[0-9]+\.[0-9]+\.[0-9]+')
          echo "version=$VERSION" >> $GITHUB_OUTPUT

      - name: Create Git tag
        run: |
          git config user.name "T1 GitHub Actions"
          git config user.email "github@t1protocol.com"
          git tag -a ${{ steps.extract.outputs.version }} -m "Release ${{ steps.extract.outputs.version }}"
          git push origin ${{ steps.extract.outputs.version }}

      - name: Create GitHub Release with Notes
        uses: release-drafter/release-drafter@v5
        with:
          tag: ${{ steps.extract.outputs.version }}
          name: Release ${{ steps.extract.outputs.version }}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}